version: '3.2'

services:
  mongo:
    container_name: economato-social-db
    image: mongo
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'user'
      MONGO_INITDB_ROOT_PASSWORD: 'password'
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
